language: node_js
env:
  global:
   
matrix:
  include:
  - node_js: '12'
cache:
  directories: [node_modules]
install:
  npm install
deploy:
  provider: heroku
  app:
    master: mighty-harbor-55894
  app_key: 7444b7b2-61ae-46c5-a907-70c4fcb74ff2